from django.db import models


class Cards(models.Model):
    customer = models.IntegerField(null=False)
    content_1 = models.FloatField(null=True, blank=True)
    content_2 = models.FloatField(null=True, blank=True)
    content_3 = models.FloatField(null=True, blank=True)
    content_4 = models.FloatField(null=True, blank=True)
    content_5 = models.FloatField(null=True, blank=True)
    content_6 = models.FloatField(null=True, blank=True)
    content_7 = models.FloatField(null=True, blank=True)
    content_8 = models.FloatField(null=True, blank=True)
    content_9 = models.FloatField(null=True, blank=True)
    express_no_transactions = models.IntegerField(null=True)
    express_total_spend = models.FloatField(null=True)
    metro_no_transactions = models.IntegerField(null=True)
    metro_total_spend = models.FloatField(null=True)
    superstore_no_transactions = models.IntegerField(null=True)
    superstore_total_spend = models.FloatField(null=True)
    extra_no_transactions = models.IntegerField(null=True)
    extra_total_spend = models.FloatField(null=True)
    fandf_no_transactions = models.IntegerField(null=True)
    fandf_total_spend = models.FloatField(null=True)
    petrol_no_transactions = models.IntegerField(null=True)
    petrol_total_spend = models.FloatField(null=True)
    direct_no_transactions = models.IntegerField(null=True)
    direct_total_spend = models.FloatField(null=True)
    gender = models.CharField(max_length=100)
    affluency = models.CharField(max_length=100)
    county = models.CharField(max_length=100)