# Generated by Django 3.0.3 on 2020-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('content_1', models.FloatField(null=True)),
                ('content_2', models.FloatField(null=True)),
                ('content_3', models.FloatField(null=True)),
                ('content_4', models.FloatField(null=True)),
                ('content_5', models.FloatField(null=True)),
                ('content_6', models.FloatField(null=True)),
                ('content_7', models.FloatField(null=True)),
                ('content_8', models.FloatField(null=True)),
                ('content_9', models.FloatField(null=True)),
                ('express_no_transactions', models.IntegerField(null=True)),
                ('express_total_spend', models.FloatField(null=True)),
                ('metro_no_transactions', models.IntegerField(null=True)),
                ('metro_total_spend', models.FloatField(null=True)),
                ('superstore_no_transactions', models.IntegerField(null=True)),
                ('superstore_total_spend', models.FloatField(null=True)),
                ('extra_no_transactions', models.IntegerField(null=True)),
                ('extra_total_spend', models.FloatField(null=True)),
                ('fandf_no_transactions', models.IntegerField(null=True)),
                ('fandf_total_spend', models.FloatField(null=True)),
                ('petrol_no_transactions', models.IntegerField(null=True)),
                ('petrol_total_spend', models.FloatField(null=True)),
                ('direct_no_transactions', models.IntegerField(null=True)),
                ('direct_total_spend', models.FloatField(null=True)),
                ('gender', models.CharField(max_length=100)),
                ('affluency', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
            ],
        ),
    ]
