# Generated by Django 3.0.3 on 2020-06-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='content_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='content_9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
